INSERT INTO CATEGORY(id, name) VALUES (category_seq.nextval, 'Reggeli');
INSERT INTO CATEGORY(id, name) VALUES (category_seq.nextval, 'Ebéd');
INSERT INTO CATEGORY(id, name) VALUES (category_seq.nextval, 'Vacsora');
INSERT INTO CATEGORY(id, name) VALUES (category_seq.nextval, 'Egészséges');
INSERT INTO CATEGORY(id, name) VALUES (category_seq.nextval, 'Könnyen elkészíthető');
INSERT INTO CATEGORY(id, name) VALUES (category_seq.nextval, 'Olcsó');
INSERT INTO CATEGORY(id, name) VALUES (category_seq.nextval, 'Gyors');
INSERT INTO CATEGORY(id, name) VALUES (category_seq.nextval, 'Előételek');
INSERT INTO CATEGORY(id, name) VALUES (category_seq.nextval, 'Levesek');
INSERT INTO CATEGORY(id, name) VALUES (category_seq.nextval, 'Saláta');
INSERT INTO CATEGORY(id, name) VALUES (category_seq.nextval, 'Csirkéből készült ételek');
INSERT INTO CATEGORY(id, name) VALUES (category_seq.nextval, 'Marhából készült ételek');
INSERT INTO CATEGORY(id, name) VALUES (category_seq.nextval, 'Sertésből készült ételek');
INSERT INTO CATEGORY(id, name) VALUES (category_seq.nextval, 'Vegetáriánus ételek');