--forras: https://www.kalóriaguru.hu/kaloriatablazat/halak-es-tenger-gyumolcsei-kaloriatablazat.php
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Abalone kagyló',105,17.1,0.8,6.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Ajóka',131,20.4,4.8,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Amerikai alóza',197,16.9,13.8,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Angolna',184,18.4,11.7,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Cápa',130,21.0,4.5,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csattogóhal',100,20.5,1.3,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csuka',88,19.3,0.7,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Dungeness rák',86,17.4,1.0,0.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Édesvízi rák',77,15.9,0.9,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Éticsiga',90,16.1,1.4,2.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Farkashal',96,17.5,2.4,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Fésűkagyló',69,12.1,0.5,3.2,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Garnélarák',85,20.1,0.5,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Harcsa',95,16.4,2.8,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Hering',158,18.0,9.0,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Homár',77,16.5,0.8,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kagyló',86,14.6,0.9,3.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kardhal',144,19.7,6.7,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kaviár (fekete, vörös)',264,24.6,17.9,4.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kék rák',87,18.1,1.1,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Királyrák',90,18.5,1.2,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Lazac',131,22.3,4.7,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Lepényhal',70,12.4,1.9,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Makrahal',85,18.5,0.7,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Makréla',205,18.6,13.9,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Nagy maréna',134,19.1,5.9,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Óriás laposhal',116,20.5,2.9,1.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Oriás rombuszhal',95,16.1,3.0,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Osztriga',81,9.5,2.3,5.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Ördöghal',97,11.7,5.3,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pisztráng',110,21.2,2.7,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Polip',82,14.9,1.0,2.2,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pompano hal',164,18.5,9.5,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Ponty',127,17.8,5.6,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Sügér',91,19.4,0.9,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Szardínia (konzerv, olajos)',208,24.6,11.5,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Szardínia (konzerv, paradicsomos)',185,20.9,10.5,0.4,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tilápia',96,20.1,1.7,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tintahal',92,15.6,1.4,3.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tokhal',105,16.1,4.0,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tonhal',144,23.3,4.9,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tőkehal',72,17.5,0.2,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Vajhal',146,17.3,8.0,0.0,'GRAM');