--forras: https://www.kalóriaguru.hu/kaloriatablazat/tesztak-kaloriatablazat.php
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Durumtészta (főtt)',158,5.4,0.6,32.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Durumtészta (száraz)',360,12.5,1.4,73.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kukoricatészta (főtt)',126,2.6,0.7,23.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kukoricatészta (száraz)',357,7.5,2.1,68.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kuszkusz (főtt)',112,3.8,0.2,21.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kuszkusz (száraz)',376,12.8,0.6,72.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Leveles tészta (fagyasztott)',423,6.0,29.0,34.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Makaróni (főtt)',158,5.8,0.9,29.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Makaróni (száraz)',371,13.0,1.5,71.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Metélt tészta (főtt)',138,4.5,2.1,24.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Metélt tészta (száraz)',384,14.2,4.4,68.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Penne tészta (főtt)',156,5.4,0.6,31.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Penne tészta (száraz)',360,12.5,1.4,73.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Quinoa (főtt)',120,4.4,1.9,18.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Quinoa (száraz)',368,14.1,6.1,57.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Rétestészta, réteslap (fagyasztott)',328,9.5,3.6,64.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Rizstészta (főtt)',108,1.8,0.2,23.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Rizstészta (száraz)',364,6.0,0.6,78.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Soba tészta (főtt)',99,5.1,0.1,21.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Soba tészta (száraz)',336,14.4,0.7,74.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Somen tészta (főtt)',131,4.0,0.2,26.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Somen tészta (száraz)',356,11.4,0.8,69.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Spagetti (főtt)',158,5.8,0.9,29.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Spagetti (száraz)',371,13.0,1.5,71.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Száraztészta (2 tojásos)',370,12.6,1.6,75.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Száraztészta (4 tojásos)',381,13.0,2.0,76.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Száraztészta (8 tojásos)',388,14.5,3.4,73.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Tarhonya (főtt)',138,5.5,1.0,27.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Tarhonya (száraz)',342,12.9,2.7,66.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Teljes kiőrlésű tészta (főtt)',149,6.0,1.7,26.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Teljes kiőrlésű tészta (száraz)',352,13.9,2.9,64.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Üvegtészta (főtt)',200,0.0,0.0,49.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Üvegtészta (száraz)',351,0.1,0.1,86.8,'GRAM');