--forras: https://www.kalóriaguru.hu/kaloriatablazat/fuszerek-kaloriatablazat.php
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Ánizs',337,17.6,15.9,35.4,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Babérlevél',313,7.6,8.4,48.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Bazsalikom',23,3.1,0.6,1.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Bazsalikom (szárított)',233,23.0,4.1,10.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Borsfű (szárított)',272,6.7,5.9,23.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Borsmenta (friss)',70,3.8,0.9,6.9,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Cayenne bors',318,12.0,17.3,29.4,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Citromfű (friss)',99,1.8,0.4,25.3,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Currypor',325,14.3,14.0,2.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csilipor',282,13.5,14.3,14.9,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Édeskömény',345,15.8,14.9,12.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Fahéj',247,4.0,1.2,27.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Fehér bors',296,10.4,2.1,42.4,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Fekete bors',251,10.4,3.3,38.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Fodormenta (friss)',44,3.3,0.7,1.6,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Fodormenta (szárított)',285,19.9,6.0,22.2,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Fokhagymapor',331,16.6,0.7,63.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Görögszénamag',323,23.0,6.4,33.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Gyömbér (őrölt)',335,9.0,4.2,57.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kakukkfű (szárított)',276,9.1,7.4,26.9,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kapor (szárított)',253,20.0,4.4,42.2,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kapribogyó',23,2.4,0.9,1.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Korianderlevél (friss)',23,2.1,0.5,0.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Korianderlevél (szárított)',279,21.9,4.7,41.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Koriandermag',298,12.4,17.8,13.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kömény',333,19.8,14.6,11.9,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kurkuma (őrölt)',312,9.7,3.3,44.4,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Majoranna (szárított)',271,12.7,7.0,20.3,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Mustármag',508,26.1,36.2,15.9,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Oregánó (szárított)',265,9.0,4.3,26.4,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Petrezselyem (szárított)',292,26.6,5.5,23.9,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Piros paprika (őrölt)',282,14.1,12.9,19.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Római kömény',375,17.8,22.3,33.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Rozmaring (szárított)',331,4.9,15.2,21.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Sáfrány',310,11.4,5.9,61.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Só',0,0.0,0.0,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Szegfűbors',263,6.0,8.6,72.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Szegfűszeg (őrölt)',274,6.0,13.0,31.6,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Szerecsendió (őrölt)',525,5.8,36.3,28.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tárkony (szárított)',295,22.8,7.2,42.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Turbolya (szárított)',237,23.2,3.9,37.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Vaníliakivonat',288,0.1,0.1,12.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Vöröshagymapor',341,10.4,1.0,63.9,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Zsálya (szárított)',315,10.6,12.8,20.4,'GRAM');