--forras: https://www.kalóriaguru.hu/kaloriatablazat/tesztak-kaloriatablazat.php
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Durumtészta (főtt)',158,5.4,0.6,32.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Durumtészta (száraz)',360,12.5,1.4,73.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kukoricatészta (főtt)',126,2.6,0.7,23.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kukoricatészta (száraz)',357,7.5,2.1,68.3,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kuszkusz (főtt)',112,3.8,0.2,21.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kuszkusz (száraz)',376,12.8,0.6,72.4,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Leveles tészta (fagyasztott)',423,6.0,29.0,34.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Makaróni (főtt)',158,5.8,0.9,29.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Makaróni (száraz)',371,13.0,1.5,71.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Metélt tészta (főtt)',138,4.5,2.1,24.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Metélt tészta (száraz)',384,14.2,4.4,68.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Penne tészta (főtt)',156,5.4,0.6,31.6,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Penne tészta (száraz)',360,12.5,1.4,73.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Quinoa (főtt)',120,4.4,1.9,18.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Quinoa (száraz)',368,14.1,6.1,57.2,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Rétestészta, réteslap (fagyasztott)',328,9.5,3.6,64.2,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Rizstészta (főtt)',108,1.8,0.2,23.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Rizstészta (száraz)',364,6.0,0.6,78.6,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Soba tészta (főtt)',99,5.1,0.1,21.4,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Soba tészta (száraz)',336,14.4,0.7,74.6,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Somen tészta (főtt)',131,4.0,0.2,26.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Somen tészta (száraz)',356,11.4,0.8,69.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Spagetti (főtt)',158,5.8,0.9,29.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Spagetti (száraz)',371,13.0,1.5,71.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Száraztészta (2 tojásos)',370,12.6,1.6,75.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Száraztészta (4 tojásos)',381,13.0,2.0,76.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Száraztészta (8 tojásos)',388,14.5,3.4,73.2,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tarhonya (főtt)',138,5.5,1.0,27.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tarhonya (száraz)',342,12.9,2.7,66.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Teljes kiőrlésű tészta (főtt)',149,6.0,1.7,26.2,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Teljes kiőrlésű tészta (száraz)',352,13.9,2.9,64.2,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Üvegtészta (főtt)',200,0.0,0.0,49.2,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Üvegtészta (száraz)',351,0.1,0.1,86.8,'GRAM');