--forras: https://www.kalóriaguru.hu/kaloriatablazat/edessegek-es-ropogtatnivalok-kaloriatablazat.php
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Babapiskóta',380,8.0,4.0,78.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Chips (burgonya)',536,7.0,34.6,48.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Chips (tortilla)',503,7.8,23.4,60.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Cukorkák',373,0.0,3.4,85.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Drazsék',448,2.0,12.0,81.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Édes aprósütemények',491,6.4,24.5,60.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Édeskeksz',483,6.3,21.0,66.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Étcsokoládé (45-59% kakaótartalmú)',546,4.9,31.3,54.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Étcsokoládé (60-69% kakaótartalmú)',579,6.1,38.3,44.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Étcsokoládé (70-85% kakaótartalmú)',598,7.8,42.6,35.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Extrudált kukoricapehely',510,5.8,26.9,61.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Fehércsokoládé',539,5.9,32.1,59.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Főzőcsokoládé',554,6.0,38.0,42.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Gumicukor',336,4.3,0.1,76.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Halva',530,15.0,35.0,47.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Háztartási keksz',430,7.0,8.9,79.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Linzer',429,5.2,21.3,54.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Mályvacukor',318,1.8,0.2,81.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Marcipánmassza',449,8.1,20.0,56.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Medvecukor',338,5.0,0.6,77.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Mézespuszedli',368,7.1,2.0,79.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Mirelit gesztenyemassza',200,2.0,1.8,44.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Mogyorókrém',541,5.4,29.7,56.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Mogyoróvaj',598,22.2,51.4,17.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Nápolyi',511,6.3,28.0,55.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Parány',501,5.1,30.8,50.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Perec',373,11.0,4.1,71.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Popcorn',387,12.9,4.5,63.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Rágógumi',360,0.0,0.3,94.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Ropi',374,11.0,3.7,72.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sajtostallér',389,13.0,8.3,62.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Tejcsokoládé',535,7.7,29.7,56.0,'GRAM');