--forras: https://www.kalóriaguru.hu/kaloriatablazat/marha-kaloriatablazat.php
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marha fehérpecsenye',121,23.4,3.0,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marha feketepecsenye',128,22.2,3.7,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marha hasaalja',155,21.2,7.2,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marha lapos hátszín',155,22.3,6.6,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marha magas hátszín',154,21.9,7.4,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhabélszín',149,21.7,6.9,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhacomb',129,22.2,3.8,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhafaggyú',902,0.0,100.0,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhafartő',195,20.6,11.9,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhagyomor',77,14.9,2.0,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhahús (közepesen zsíros)',215,18.6,15.0,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhahús (sovány)',137,21.4,5.0,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhahús (zsíros)',332,14.4,30.0,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhalábszár',128,21.8,3.9,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhalapocka',152,20.1,8.1,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhalép',105,18.3,3.0,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhamáj',135,20.4,3.6,3.9,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhanyelv',224,14.9,16.1,3.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhaszegy',251,18.4,19.1,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhaszív',112,17.7,3.9,0.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhatarja',216,25.7,11.7,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhatüdő',92,16.2,2.5,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhavelő',143,10.9,10.3,1.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Marhavese',99,17.4,3.1,0.3,'GRAM');
