--forras: https://www.kalóriaguru.hu/kaloriatablazat/huskeszitmenyek-kaloriatablazat.php
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Baromfi párizsi',130,10.6,14.0,2.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Baromfi virsli',193,12.0,15.0,2.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Chorizo kolbász',433,23.7,35.1,5.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Csabai kolbász',494,23.0,44.0,0.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Császárszalonna',367,12.0,35.0,1.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Cserkészkolbász',336,16.3,29.8,0.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Disznósajt',249,17.0,20.0,0.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Főzőkolbász',301,14.8,27.3,2.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Füstölt kolbász',316,28.3,22.4,0.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Gépsonka',88,15.5,2.8,1.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Gyulai kolbász',479,22.0,43.0,1.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Házi szárazkolbász',469,20.0,43.0,0.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Húskenyér',303,9.2,27.4,4.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Húspástétom',282,13.0,23.0,6.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kacsamájkrém',282,8.5,26.0,3.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Krinolin',206,13.0,16.0,3.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Lecsókolbász',409,16.4,36.5,3.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Libamájkrém',194,9.1,16.1,2.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Löncshús',176,9.3,15.4,0.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Májashurka',379,14.6,34.5,1.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Marha párizsi',216,11.3,18.5,1.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Mortadella',322,16.0,28.4,0.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Nyári szalámi',362,16.2,32.6,1.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Olasz felvágott',251,13.1,21.6,1.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Paprikás szalámi',520,24.0,47.0,0.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Paraszt sonka',245,20.0,18.0,0.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Pármai sonka',236,26.8,14.1,0.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Pulykakolbász',270,12.0,24.0,1.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Pulykapárizsi',203,11.0,17.0,1.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Pulykasonka',111,15.0,4.0,3.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Pulykavirsli',236,13.0,20.0,0.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertés párizsi',207,12.0,17.0,1.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertés virsli',252,13.0,21.0,2.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertésmájkrém',237,10.5,15.5,13.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sütnivaló kolbász',346,14.3,31.3,0.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Szafaládé',250,10.1,22.4,2.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Szárazkolbász',494,23.0,44.0,0.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Tavaszi felvágott',209,12.0,17.0,1.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Téliszalámi',524,25.0,47.0,0.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Turista felvágott',372,18.0,33.0,1.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Turista szalámi',362,16.2,32.6,1.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Vaddisznókolbász',500,22.0,42.0,1.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Véreshurka',250,12.2,19.4,6.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Veronai felvágott',288,15.0,24.0,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Zalai felvágott',218,13.0,18.0,1.1,'GRAM');