--forras: https://www.kalóriaguru.hu/kaloriatablazat/tojas-kaloriatablazat.php
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Buggyantott tojás',143,12.5,9.4,0.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Buggyantott tojás (db)',76,6.6,5,0.4,'PIECE');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Főtt tojás',155,12.5,10.6,1.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Főtt tojás (db)',82,6.6,5.6,0.6,'PIECE');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Fürjtojás',158,13.1,11.1,0.4,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Fürjtojás (db)',16,1.3,1.1,0,'PIECE');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kacsatojás',185,12.8,13.8,1.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kacsatojás (db)',130,9,9.7,1,'PIECE');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Libatojás',185,13.9,13.3,1.4,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Libatojás (db)',266,20,19.2,2,'PIECE');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykatojás',171,13.7,11.9,1.2,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykatojás (db)',135,10.8,9.4,0.9,'PIECE');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tyúktojás',143,12.6,9.5,0.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tyúktojás (db)',76,6.5,5,0.4,'PIECE');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tyúktojás (tojásfehérje)',52,10.9,0.2,0.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tyúktojás (tojásfehérje - db)',16,3.4,0.1,0.2,'PIECE');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tyúktojás (tojásfehérje, por)',382,81.1,0.0,7.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tyúktojás (por)',592,48.1,43.9,1.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tyúktojás (tojássárgája)',322,15.9,26.5,3.6,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tyúktojás (tojássárgája - db)',71,3.5,5.8,0.8,'PIECE');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tyúktojás (tojássárgája, por)',669,33.6,59.1,0.7,'GRAM');