--forras: https://www.kalóriaguru.hu/kaloriatablazat/sertes-kaloriatablazat.php
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertés hasaalja',518,9.3,53.0,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertésborda',140,20.8,5.6,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertéscomb',136,20.5,5.4,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertésfarok',378,17.8,33.5,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertésfül',234,22.5,15.1,0.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertésgyomor',159,16.9,10.1,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertéshús (közepesen zsíros)',218,18.0,16.0,0.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertéshús (sovány)',121,21.1,4.0,0.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertéshús (zsíros)',263,16.9,21.2,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertéskaraj (hosszú karaj)',155,21.6,6.9,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertéskaraj (rövid karaj)',133,22.5,4.1,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertésláb',140,11.6,10.0,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertéslapocka',148,19.6,7.1,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertéslép',100,17.9,2.6,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertésmáj',134,21.4,3.7,2.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertésnyelv',225,16.3,17.2,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertéspofa',655,6.3,69.6,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertéssonka',147,22.3,5.7,0.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertéstarja',132,18.7,5.7,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertéstoka',655,6.4,69.6,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertéstüdő',85,14.1,2.7,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertésvelő',127,10.3,9.2,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertésvese',100,16.5,3.3,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertészsír',897,0.0,99.5,0.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertésszalonna',417,12.6,39.7,1.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertésszív',118,17.3,4.4,1.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sertésszűz',120,20.7,3.5,0.0,'GRAM');