--forras: https://www.kalóriaguru.hu/kaloriatablazat/pekaruk-kaloriatablazat.php
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Abonett',360,13.0,2.3,65.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Alföldi kenyér',268,10.0,1.0,53.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Bakonyi barna kenyér',253,9.0,2.4,46.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Briós',346,8.2,10.4,54.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Burgonyás kenyér',266,12.5,3.1,40.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Búzacsírás kenyér',293,10.7,3.3,52.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Búzakorpás kenyér',248,8.8,3.4,43.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Diós csiga',386,9.0,15.0,51.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Erzsébet kenyér',246,7.0,1.0,50.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Fánk',271,5.0,10.6,38.3,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Fehér kenyér',238,10.7,2.2,34.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Félbarna kenyér',246,8.2,1.5,49.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Francia kenyér',289,11.7,1.8,56.4,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Gofri',489,8.5,28.8,48.4,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Graham kenyér',272,10.0,3.5,48.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kakaós csiga',494,7.0,24.0,59.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kalács',326,9.3,9.5,49.6,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kétszersült',389,12.0,6.3,67.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kifli',295,9.1,2.3,59.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kuglóf',352,10.0,8.7,58.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kukoricás kenyér',266,6.7,7.4,43.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Lekváros bukta',322,8.0,6.0,57.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Lenmagos barnakenyér',276,10.1,4.1,47.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Magos kenyér',288,11.0,6.7,44.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Magvas barnakenyér',285,10.8,6.5,45.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Mazsolás kenyér',274,7.9,4.4,48.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Muffin',456,4.2,27.0,49.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Olasz kenyér',271,8.8,3.5,46.9,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Palacsinta',232,5.0,12.0,25.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pirítós',389,12.0,6.3,67.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Piskótatekercs',374,4.2,12.0,62.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pita (fehér lisztből)',275,9.1,1.2,53.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pita (teljes kiőrlésű)',262,9.8,1.7,49.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pogácsa (tepertős)',430,8.0,22.0,47.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pogácsa (vajas)',437,9.0,21.0,50.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pumpernickel',250,8.7,3.1,41.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Rozskenyér',259,8.5,3.3,42.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Teljes kiőrlésű kenyér',252,12.5,3.5,36.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Teljes kiőrlésű kifli',216,7.4,4.0,41.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Teljes kiőrlésű zsemle',266,9.1,5.0,51.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Tökmagos kenyér',258,10.7,6.3,34.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Túrós batyu',310,11.0,6.0,51.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Zabkorpás kenyér',236,10.4,4.4,35.3,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Zsemle',277,9.2,0.0,57.4,'GRAM');