--forras: https://www.kalóriaguru.hu/kaloriatablazat/alkoholos-italok-kaloriatablazat.php
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Alkoholmentes bor',6,0.5,0.0,1.1,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Alkoholmentes sör',37,0.2,0.1,8.1,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Almabor',56,0.0,0.0,5.9,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Asztali bor',83,0.1,0.0,2.7,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Barna sör',35,0.3,0.0,2.8,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Fehérbor',82,0.1,0.0,2.6,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Gin',263,0.0,0.0,0.0,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Konyak',217,0.0,0.0,0.0,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Likőr',336,0.1,0.3,46.8,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Pálinka',260,0.0,0.0,0.0,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Pezsgő',65,0.2,0.0,1.0,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Rum',231,0.0,0.0,0.0,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sör',43,0.5,0.0,3.6,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sütőrum',140,0.0,0.0,0.0,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Tequila',110,0.3,0.1,11.3,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Unicum',323,0.0,0.0,19.0,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Világos sör',41,0.4,0.0,3.0,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Vodka',231,0.0,0.0,0.0,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Vörösbor',85,0.1,0.0,2.6,'MILLILITRE');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Whisky',250,0.0,0.0,0.1,'MILLILITRE');