--forras: https://www.kalóriaguru.hu/kaloriatablazat/zoldsegek-es-huvelyesek-kaloriatablazat.php
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Adzuki bab (főtt)',128,7.5,0.1,17.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Adzuki bab (száraz)',329,19.9,0.5,50.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Articsóka',47,3.3,0.2,5.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Bab (főtt)',118,8.3,0.4,14.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Bab (konzerv)',114,7.4,0.4,16.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Bab (száraz)',339,21.9,1.1,42.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Bambuszrügy',27,2.6,0.3,3.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Bambuszrügy (konzerv)',19,1.7,0.4,1.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Borsmustár (Arugula)',25,2.5,0.6,2.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Brokkoli',34,2.8,0.4,4.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Brokkoli (fagyasztott)',26,2.8,0.3,1.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Burgonya',77,2.1,0.1,15.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Burgonya (főtt)',86,1.7,0.1,18.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Burgonya (olajban sült)',172,2.7,5.2,26.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Burgonya (sütőben sült)',93,2.0,0.1,20.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Cékla',43,1.6,0.2,6.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Cékla (savanyúság)',65,0.8,0.1,15.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Cukkini',17,1.2,0.3,2.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Csemegeuborka',11,0.3,0.2,1.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Csicseriborsó (főtt)',164,8.9,2.6,19.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Csicseriborsó (konzerv)',139,7.1,2.8,16.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Csicseriborsó (száraz)',378,20.5,6.0,50.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Csicsóka',73,2.0,0.0,15.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Csili paprika (piros)',40,1.9,0.4,7.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Csili paprika (zöld)',40,2.0,0.2,8.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Csillagtök',18,1.2,0.2,2.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Disznóbab (főtt)',110,7.6,0.4,14.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Disznóbab (konzerv)',71,5.4,0.2,8.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Disznóbab (száraz)',341,26.1,1.5,33.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Édes hagyma',32,0.8,0.0,6.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Édesburgonya',86,1.5,0.0,17.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Édesburgonya (főtt)',76,1.4,0.1,15.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Édeskömény gumó',31,1.2,0.4,4.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Endívia saláta',17,1.3,0.2,0.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Étkezési paprika',27,1.0,0.2,5.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Farkasbab (főtt)',119,15.5,2.9,9.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Farkasbab (száraz)',371,36.1,9.7,40.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Favabab (főtt)',110,7.6,0.4,14.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Favabab (konzerv)',71,5.5,0.2,8.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Favabab (száraz)',341,26.1,1.5,33.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Fehérbab (főtt)',139,9.7,0.4,18.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Fehérbab (konzerv)',114,7.3,0.3,16.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Fehérbab (száraz)',333,23.4,0.9,45.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Fehérrépa',36,3.0,0.8,3.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Fejes káposzta',25,1.3,0.1,3.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Fejes saláta',15,1.4,0.2,1.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Fekete bab (főtt)',132,8.9,0.5,15.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Fekete bab (konzerv)',91,6.0,0.3,9.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Fekete bab (száraz)',341,21.6,1.4,46.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Fodros kel',42,2.8,0.6,6.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Fokhagyma',149,6.4,0.5,31.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Főzőtök',31,0.6,0.6,5.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Galambborsó (főtt)',121,6.8,0.4,16.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Galambborsó (száraz)',343,21.7,1.5,47.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Gyömbérgyökér',80,1.8,0.8,15.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Gyöngyhagyma',72,2.5,0.1,13.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Halloween tök',26,1.0,0.1,6.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Hínár',26,0.5,0.0,6.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Jácintbab (főtt)',117,8.1,0.6,20.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Jácintbab (száraz)',344,23.9,1.7,35.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Jalapeno paprika',29,0.9,0.4,4.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Jégcsapretek',14,1.1,0.1,1.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Jégsaláta',14,0.9,0.1,2.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kapor',43,3.5,1.1,4.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Karalábé',27,1.7,0.1,2.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kárdi',17,0.7,0.1,2.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Karfiol',25,1.9,0.3,3.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kelbimbó',43,3.4,0.3,5.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kelbimbó (fagyasztott)',41,3.8,0.4,4.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kelkáposzta',27,2.0,0.1,3.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kerekrépa (tarlórépa)',28,0.9,0.1,4.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kígyóuborka',15,0.7,0.1,3.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kimcshi',15,1.1,0.5,1.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kínai hosszú bab (főtt)',118,8.3,0.5,17.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kínai hosszú bab (friss)',47,2.8,0.4,8.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kínai hosszú bab (száraz)',347,24.3,1.3,50.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kínai kel (pak-choi)',13,1.5,0.2,1.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kínai kel (pe-tsai)',16,1.2,0.2,2.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Krumpli',77,2.1,0.1,15.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Krumpli (főtt)',86,1.7,0.1,18.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Krumpli (olajban sült)',172,2.7,5.2,26.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Krumpli (sütőben sült)',93,2.0,0.1,20.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kukorica (fagyasztott)',80,2.8,0.4,17.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kukorica (főtt)',97,3.3,1.4,19.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kukorica (konzerv)',79,2.4,0.5,17.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kukorica (nyers)',86,3.2,1.2,16.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Kukorica (száraz)',365,9.4,4.7,74.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Lencse (főtt)',116,9.0,0.4,12.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Lencse (száraz)',352,24.6,1.1,52.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Leveles kel',42,2.8,0.6,6.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Lilahagyma',42,0.9,0.1,10.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Lilakáposzta',31,1.4,0.2,5.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Limabab (főtt)',115,7.8,0.4,13.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Limabab (konzerv)',79,4.9,0.2,10.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Limabab (száraz)',338,21.5,0.7,44.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Lóbab',88,7.9,0.7,10.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Makktök',40,0.8,0.1,8.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Malabár spenótlevél',19,1.8,0.3,3.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Mangold',19,1.8,0.2,2.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Manióka',160,1.3,0.2,36.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Medvehagyma',19,0.9,0.3,2.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Metélőhagyma',30,3.3,0.7,1.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Mungóbab (főtt)',105,7.0,0.4,11.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Mungóbab (száraz)',347,23.9,1.2,46.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Okra',33,1.9,0.2,4.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Olívabogyó (konzerv)',115,0.8,10.7,3.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Padlizsán',25,1.0,0.2,3.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Pálmaszív',115,2.7,0.2,24.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Pálmaszív (konzerv)',28,2.5,0.6,2.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Paprika',27,1.0,0.2,5.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Paradicsom',18,0.9,0.2,1.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Paradicsomlé',17,0.9,0.3,3.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Paradicsompüré',38,1.7,0.2,7.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Pasilla paprika (szárított)',345,12.3,15.8,24.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Paszternák',75,1.2,0.3,13.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Patiszon',18,1.2,0.2,2.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Petrezselyem zöldje',32,1.5,0.3,7.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Pézsmatök',45,1.0,0.1,9.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Pintó bab (főtt)',143,9.0,0.7,17.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Pintó bab (konzerv)',117,7.0,1.0,15.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Pintó bab (száraz)',347,21.4,1.2,47.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Piros fejes saláta',16,1.3,0.2,1.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Poblano paprika (szárított)',281,11.8,8.2,29.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Póréhagyma',61,1.5,0.3,12.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Rebarbara',21,0.9,0.2,2.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Retek',16,0.7,0.1,1.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Római bab (főtt)',136,9.3,0.5,15.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Római bab (konzerv)',83,5.5,0.3,8.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Római bab (száraz)',335,23.0,1.2,35.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Római saláta',17,1.2,0.3,1.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Rózsaszín bab (főtt)',149,9.1,0.5,22.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Rózsaszín bab (száraz)',343,21.0,1.1,51.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Rukkola',25,2.6,0.7,2.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sárgabab (fagyasztott)',28,1.4,0.1,3.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sárgabab (főtt)',35,1.9,0.3,4.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sárgabab (konzerv)',20,1.1,0.1,3.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sárgabab (száraz)',31,1.8,0.1,3.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sárgaborsó (főtt)',118,8.3,0.4,12.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sárgaborsó (száraz)',352,23.8,1.2,38.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sárgarépa',41,0.9,0.2,6.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sárgarépa (főtt)',37,0.5,0.6,4.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sárgarépalé',40,1.0,0.2,8.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Savanyú káposzta',19,0.9,0.1,4.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Savanyú uborka',11,0.3,0.2,1.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Serrano paprika',32,1.7,0.4,3.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Snidling',30,3.3,0.7,1.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sóska',22,2.0,0.7,3.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Spárga',20,2.2,0.1,1.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Spárgatök',31,0.6,0.6,5.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Spenót (fagyasztott)',29,3.6,0.6,1.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Spenótlevél',23,2.9,0.4,1.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sűrített paradicsom 15-17%',40,2.4,0.2,6.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sűrített paradicsom 18-20%',61,3.1,0.6,9.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sűrített paradicsom 28-30%',87,4.0,0.8,16.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Sütőtök',45,1.0,0.1,9.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Szárnyasbab (főtt)',147,10.6,5.8,14.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Szárnyasbab (száraz)',409,29.7,16.3,15.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Tarkabab (konzerv)',95,6.8,0.9,11.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Tarkabab (száraz)',353,21.0,1.0,63.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Tehénbab (főtt)',117,7.8,0.5,20.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Tehénbab (száraz)',343,22.9,1.6,61.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Tehénborsó (főtt)',117,8.1,0.7,16.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Tehénborsó (száraz)',343,23.9,2.1,48.9,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Tengerészbab (főtt)',140,8.2,0.7,15.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Tengerészbab (konzerv)',113,7.5,0.4,15.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Tengerészbab (száraz)',337,22.3,1.5,45.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Torma',48,1.2,0.7,8.0,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Tök',16,1.2,0.2,2.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Uborka',11,0.3,0.2,1.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Újhagyma',32,1.8,0.2,4.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Vesebab (főtt)',127,8.7,0.5,16.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Vesebab (konzerv)',84,5.2,0.8,10.2,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Vesebab (száraz)',333,23.6,0.8,35.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Vörös káposzta',31,1.4,0.2,5.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Vörösbab (főtt)',127,8.7,0.5,15.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Vörösbab (konzerv)',81,5.2,0.4,10.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Vörösbab (száraz)',337,22.5,1.1,46.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Vöröshagyma',40,1.1,0.1,7.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Vöröslencse (főtt)',111,7.4,0.7,19.6,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Vöröslencse (száraz)',358,23.9,2.2,52.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Wasabi gyökér',109,4.8,0.6,15.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Yamgyökér',67,1.3,0.1,13.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Zeller gyökér',42,1.5,0.3,7.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Zeller zöldje',16,0.7,0.2,1.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Zöldbab (fagyasztott)',28,1.5,0.2,3.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Zöldbab (főtt)',35,1.9,0.3,4.7,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Zöldbab (konzerv)',22,1.1,0.5,2.4,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Zöldbab (nyers)',31,1.8,0.2,4.3,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Zöldborsó (fagyasztott)',78,5.2,0.3,9.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Zöldborsó (főtt)',84,5.4,0.2,10.1,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Zöldborsó (konzerv)',69,4.4,0.4,8.5,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Zöldborsó (nyers)',81,5.4,0.4,8.8,'GRAM');
INSERT INTO INGREDIENT(id, name,energyKcal,protein,fat,carbohydrate,unit) VALUES (ingredient_seq.nextval,'Zöldpaprika',20,0.9,0.2,2.9,'GRAM');