--forras: https://www.kalóriaguru.hu/kaloriatablazat/szarnyasok-kaloriatablazat.php
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirke alsócomb',116,19.4,3.7,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirke alsócomb (bőrrel)',161,18.1,9.2,0.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirke felsőcomb',121,19.7,4.1,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirke felsőcomb (bőrrel)',221,16.5,16.6,0.3,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkeaprólék',124,17.8,4.4,1.8,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkebőr',349,13.3,32.4,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkecomb',119,19.5,3.9,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkecomb (bőrrel)',191,17.3,12.9,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkehát',137,19.6,5.9,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkehát (bőrrel)',319,14.1,28.7,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkehús',119,21.4,3.1,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkeláb',120,19.1,4.2,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkemáj',119,16.9,4.8,0.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkemell',120,22.5,2.6,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkemell (bőrrel)',172,20.9,9.3,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkenyak',213,18.3,14.8,0.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkeszárny',126,22.0,3.5,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkeszárny (bőrrel)',191,17.5,12.9,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkeszív',153,15.6,9.3,0.7,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Csirkezúza',94,17.7,2.1,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Fácánhús',133,23.6,3.6,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Fürjhús',134,21.8,4.5,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Galambhús',142,17.5,7.5,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kacsahús',135,18.3,6.0,0.9,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Kacsamáj',136,18.7,4.6,3.5,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Libahús',161,22.8,7.1,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Libamáj',133,16.4,4.3,6.3,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulyka alsócomb',118,20.5,3.9,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulyka alsócomb (bőrrel)',141,19.9,6.8,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulyka felsőcomb',116,20.6,3.6,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulyka felsőcomb (bőrrel)',161,19.5,9.1,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykabőr',407,13.0,38.9,0.2,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykacomb',117,20.6,3.8,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykacomb (bőrrel)',151,19.8,8.0,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykahát',113,21.3,2.5,0.2,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykahát (bőrrel)',206,16.9,15.4,0.2,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykahús',114,23.7,1.5,0.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykaláb',144,19.5,6.7,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykamáj',128,18.3,5.5,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykamell',114,23.3,2.3,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykamell (bőrrel)',155,21.9,7.5,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykanyak',125,16.5,6.0,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykaszárny',112,22.5,2.5,0.0,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykaszárny (bőrrel)',202,19.5,13.8,0.1,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykaszív',140,16.7,7.4,0.4,'GRAM');
INSERT INTO INGREDIENT(name,energyKcal,protein,fat,carbohydrate,unit) VALUES ('Pulykazúza',111,18.8,3.4,0.0,'GRAM');