INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval, 'Francia konyha', 'France.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval,'Olasz konyha', 'Italy.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval,'Angol konyha', 'UnitedKingdom.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval,'Német konyha', 'Germany.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval,'Osztrák konyha', 'Austria.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval,'Svájci konyha', 'Switzerland.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval,'Spanyol konyha', 'Spain.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval,'Görög konyha', 'Greece.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval,'Török konyha', 'Turkey.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval,'Román konyha', 'Romania.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval,'Orosz konyha', 'Russia.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval,'Lengyel konyha', 'Poland.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval,'Japán konyha', 'Japan.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval,'Kínai konyha', 'China.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval,'Amerikai konyha', 'UnitedStates.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (cuisine_seq.nextval,'Magyar konyha', 'Hungary.png');