INSERT INTO CUISINE(id, name,icon_file_name) VALUES (1, 'Francia konyha', 'France.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (2,'Olasz konyha', 'Italy.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (3,'Angol konyha', 'UnitedKingdom.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (4,'Német konyha', 'Germany.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (5,'Osztrák konyha', 'Austria.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (6,'Svájci konyha', 'Switzerland.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (7,'Spanyol konyha', 'Spain.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (8,'Görög konyha', 'Greece.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (9,'Török konyha', 'Turkey.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (10,'Román konyha', 'Romania.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (11,'Orosz konyha', 'Russia.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (12,'Lengyel konyha', 'Poland.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (13,'Japán konyha', 'Japan.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (14,'Kínai konyha', 'China.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (15,'Amerikai konyha', 'UnitedStates.png');
INSERT INTO CUISINE(id, name,icon_file_name) VALUES (16,'Magyar konyha', 'Hungary.png');